# ===============================
# Application
# ===============================
spring.application.name=CATALOG-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/washgo_catalog_db
spring.datasource.username=postgres
spring.datasource.password=root

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE