# ===============================
# Application
# ===============================
spring.application.name=PAYMENT-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===============================
# Server
# ===============================
server.port=8085

# ===============================
# Order Service
# ===============================
# Keep localhost for now if you are still using RestTemplate/WebClient.
# Change to lb://ORDER-SERVICE when we implement OpenFeign/LoadBalancer.
order.base-url=http://localhost:8083

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/washgo_payment_db
spring.datasource.username=postgres
spring.datasource.password=aaa
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Remove this (Hibernate 6 detects PostgreSQL automatically)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Jackson
# ===============================
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=Asia/Kolkata

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# Swagger
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# ===============================
# Razorpay
# ===============================
razorpay.key-id=rzp_test_TFJKp9t9jnblPr
razorpay.key-secret=LHw678jl2FEAweUmOBTf9oWY
razorpay.currency=INR

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always